# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: fszteam.megacompany::lang.employee.label

# Model Form Field configuration
form: $/fszteam/megacompany/models/employee/fields.yaml

# Model Class name
modelClass: FszTeam\MegaCompany\Models\Employee

# Default redirect location
defaultRedirect: fszteam/megacompany/employees

# Create page
create:
    title: fszteam.megacompany::lang.employee.create_title
    redirect: fszteam/megacompany/employees/update/:id
    redirectClose: fszteam/megacompany/employees

# Update page
update:
    title: fszteam.megacompany::lang.employee.update_title
    redirect: fszteam/megacompany/employees
    redirectClose: fszteam/megacompany/employees

# Preview page
preview:
    title: fszteam.megacompany::lang.employee.preview_title