# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: fszteam.megacompany::lang.gallery.label

# Model Form Field configuration
form: $/fszteam/megacompany/models/gallery/fields.yaml

# Model Class name
modelClass: FszTeam\MegaCompany\Models\Gallery

# Default redirect location
defaultRedirect: fszteam/megacompany/galleries

# Create page
create:
    title: fszteam.megacompany::lang.gallery.create_title
    redirect: fszteam/megacompany/galleries/update/:id
    redirectClose: fszteam/megacompany/galleries

# Update page
update:
    title: fszteam.megacompany::lang.gallery.update_title
    redirect: fszteam/megacompany/galleries
    redirectClose: fszteam/megacompany/galleries

# Preview page
preview:
    title: fszteam.megacompany::lang.gallery.preview_title